name = "construpro-worker"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
ENVIRONMENT = "production"

[[d1_databases]]
binding       = "DB"
database_name = "construFY-db"
database_id   = "87050e49-29d9-459a-a7d4-4cdfe42e4484"

[[kv_namespaces]]
binding = "RATE_KV"
id      = "32d4a3cb8a4c4f909064d0f8654cc88c"

[triggers]
crons = ["0 3 * * *"]